### ISSUE TITLE
Doesn't work well for wildcard oredicts

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/OreDictDumper#3]
For example with GT6, `craftingHardenedClay` is a wildcard oredict for all the colored hardened clays, but all that this mod dumps is: `craftingHardenedClay!Black Stained Clay!V!!`.

Please fix.

**Comment by elifoster** [comment]
Does this happen on all versions or just 1.7?

**Comment by elifoster** [comment]
Closed by b81a741(1.9), 6b04569 (1.8), and 939a15b (1.7).
